title: wiki
description: my wiki
show_downloads: true
git_branch: master
logo_url: https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Wikipedia-logo-v2.svg/1122px-Wikipedia-logo-v2.svg.png
google_analytics:
wiki_folder: wiki
custom_head: false
custom_sidebar: false
custom_footer: false
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag